version: "3.8"

services:
  bot:
    build: ./app
    image: points-bot
    env_file: ./.env
    environment:
      MYSQL_HOST: mysqldb
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql
    restart: always
    env_file: ./.env
    ports:
      - $MYSQL_PORT:$MYSQL_PORT
    volumes:
      - db:/var/lib/mysql

volumes:
  db: